/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app.characters.index'
import { Route as AppCharactersNewRouteImport } from './routes/_app.characters.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersNewRoute = AppCharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/characters/new': typeof AppCharactersNewRoute
  '/characters/': typeof AppCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/characters/new': typeof AppCharactersNewRoute
  '/characters': typeof AppCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/characters/new': typeof AppCharactersNewRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/characters/new' | '/characters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/characters/new' | '/characters'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/characters/new'
    | '/_app/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/characters/new': {
      id: '/_app/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof AppCharactersNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCharactersNewRoute: typeof AppCharactersNewRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCharactersNewRoute: AppCharactersNewRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
